---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Income prediction

In this homework, you are required to analyze and visualize a dataset describing a person's income. In this dataset,  **more than 30,000** real records are collected. The attributes of each record include age, education, occupation, race, sex and so on. Note that some information is missed and was recorded as NaN. Please follow the start code of this project and finish the rest.

Through this project, you are expected to have a better command of these fields:
- Exploratory Data Analysis
- Visualization

The attribute information is:

- **income**: the label of this dataset, belongs to \[high, low\] 
- **age**: the age of a person, a continuous variable.
- **work_class**: work class, belongs to \[Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked\].
- **education**: belongs to \[Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, - Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool\].
- **education_degree**: the education level of a person, an ordinal number variable.
- **marital_status**: marital status, belongs to \[Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse\]. 
- **job**: occupation, belongs to \[Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces\]. 
- **relationship**: belongs to \[Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried\].
- **race**: belongs to \[White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black\]. 
- **sex**: belongs to \[Female, Male\]. 
- **capital_gain**: capital gain, a continuous variable. 
- **capital_loss**: capital loss, a continuous variable. 
- **hours_per_week**: how long a person works every week, a continuous variable. 
- **birthplace**: belongs to \[United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, - Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands\].


Specifically, you are required to **fill the blanks of this notebook** based on your results. In this assignment, you will analyze how different features, models and hyper-parameters influence the performance.


## 1. Load Data

```{python}
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn

# %matplotlib inline
# # %config InlineBackend.figure_format = 'svg'
```

```{python}
df = pd.read_csv('income.csv')
```

## 2. Exploratory Data Analysis


### Take a brief look at the data using `head()`

```{python}
df.head()
```

### Observe the basic statistical information of continuous attributes

```{python}
df.describe() # only describe the continuous variables
```

### Count the NaN values

```{python}
df.isnull().sum()  ### before
```

### Remove NaN values due to small proportion to the whole dataset

```{python}
df = df.dropna()
```

```{python}
df.isnull().sum()  ### after
```

### Pick out categorical and continuous variables

```{python}
df.info()
```

### Observe categorical attributes


* **[pandas.DataFrame.select_dtypes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html)**
* **[pandas.DataFrame.columns](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.columns.html)**

```{python}
for col in df.select_dtypes([np.object]).columns:
    print('{}: {}\n'.format(col, df[col].unique()))
```

* **[matplotlib.pyplot.subplots](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.subplots.html)**
* **[seaborn.countplot](https://seaborn.pydata.org/generated/seaborn.countplot.html)**

```{python}
fig,axes = plt.subplots(nrows=1,ncols=1,figsize=(24,18))
plt.xticks(fontsize=25)
plt.yticks(fontsize=25)
sns.countplot(y='education', data=df)
```

### Merge values of similar semantics

```{python}
df.education.replace({
    'Preschool': 'dropout',
    '10th': 'dropout',
    '11th': 'dropout',
    '12th': 'dropout',
    '1st-4th': 'dropout',
    '5th-6th': 'dropout',
    '7th-8th': 'dropout',
    '9th': 'dropout',
    'HS-Grad': 'HighGrad',
    'HS-grad': 'HighGrad',
    'Some-colloge': 'CommunityCollege',
    'Assoc-acdm': 'CommunityCollege',
    'Assoc-voc': 'CommunityCollege',
    'Prof-school': 'Masters',
}, inplace=True)
```

### Univariable Analysis 


#### Using `seaborn.countplot()` to show categorical univariable

```{python}
sns.countplot(y='education', data=df)
plt.show()
###Question 1. plot more categorical attributes including work_class and marital_status using countplot().
## 
## Your code here
sns.countplot(y='work_class', data=df)
plt.show()
sns.countplot(y='marital_status', data=df)
plt.show()
```

#### Using built-in API `plot()` of DataFrame: bar chart to show categorical univariable

```{python}
df.job.value_counts().plot(kind='bar', figsize=(8, 8), fontsize=8)
plt.show()
###Question 2. plot more categorical attributes including work_class and marital_status using bar chart.
## 
## Your code here
## 
df.work_class.value_counts().plot(kind='bar', figsize=(8, 8), fontsize=8)
plt.show()
df.marital_status.value_counts().plot(kind='bar', figsize=(8, 8), fontsize=8)
plt.show()
```

#### Using built-in API `plot()` of DataFrame: pie chart  to show categorical univariable

```{python}
df.race.value_counts().plot(kind='pie', figsize=(8, 8), fontsize=8)
plt.show()
###Question 3. plot more categorical attributes including work_class and marital_status using pie chart.
## 
## Your code here
##
df.work_class.value_counts().plot(kind='pie', figsize=(8, 8), fontsize=8)
plt.show()
df.marital_status.value_counts().plot(kind='pie', figsize=(8, 8), fontsize=8)
plt.show()
```

#### Using `seaborn.distplot()` to show continuous univariable

```{python}
sns.distplot(df.hours_per_week)
plt.show()
###Question 4. plot more (at least 1) continuous attributes using distplot, such as capital_loss, hours_per_week, etc.
## 
## Your code here
##
sns.distplot(df.age)
plt.show()
sns.distplot(df.capital_loss)
plt.show()
sns.distplot(df.capital_gain)
plt.show()
```

#### Using `plt.hist()` to show continuous univariable

```{python}
## Compare with seaborn.distplot()
plt.hist(df.hours_per_week)
plt.show()
plt.hist(df.age)
plt.show()
plt.hist(df.capital_gain)
plt.show()
plt.hist(df.capital_loss)
plt.show()
```

#### Using `seaborn.boxplot()` to show continuous univariable

```{python}
sns.boxplot(y=df.education_degree)
plt.show()
###Question 5. plot more (at least 1) continuous attributes using boxplot, such as capital_loss, hours_per_week, etc.
## 
## Your code here
##
sns.boxplot(y=df.age)
plt.show()

sns.boxplot(y=df.capital_gain)
plt.show()

sns.boxplot(y=df.capital_loss)
plt.show()

sns.boxplot(y=df.hours_per_week)
plt.show()
```

### Multivariable Analysis


#### Using `seaborn.distplot()` with different conditions to show continuous multivariable's relationship


* **[seaborn.distplot](https://seaborn.pydata.org/generated/seaborn.distplot.html#seaborn.distplot)**

```{python}
sns.distplot(df[df.income == 'high']['age'], kde_kws={'label': 'high'})
sns.distplot(df[df.income == 'low']['age'], kde_kws={'label': 'low'})
plt.show()
###Question 6. plot more (at least 1) attributes (conditioned on income) using distplot, such as capital_loss, hours_per_week, etc.
## 
## Your code here
##

sns.distplot(df[df.income == 'high']['capital_gain'], kde_kws={'label': 'high'})
sns.distplot(df[df.income == 'low']['capital_gain'], kde_kws={'label': 'low'})
plt.show()

sns.distplot(df[df.income == 'high']['capital_loss'], kde_kws={'label': 'high'})
sns.distplot(df[df.income == 'low']['capital_loss'], kde_kws={'label': 'low'})
plt.show()

sns.distplot(df[df.income == 'high']['hours_per_week'], kde_kws={'label': 'high'})
sns.distplot(df[df.income == 'low']['hours_per_week'], kde_kws={'label': 'low'})
plt.show()
```

**Using seaborn.boxplot() with different conditions to show continuous multivariable's relationship**


* **[seaborn.boxplot](https://seaborn.pydata.org/generated/seaborn.boxplot.html#seaborn.boxplot)**

```{python}
ax1 = sns.boxplot(x="income", y="age", data=df)
plt.show()
###Question 7. plot more (at least 1) attributes (conditioned on income) using boxplot, such as capital_loss, hours_per_week, etc
## 
## Your code here
## 
ax2 = sns.boxplot(x="income", y="capital_gain", data=df)
plt.show()

ax3 = sns.boxplot(x="income", y="capital_loss", data=df)
plt.show()

ax4 = sns.boxplot(x="income", y="hours_per_week", data=df)
plt.show()
```

**Using seaborn.scatterplot() to show the relationship between different continuous multivariable**


* **[seaborn.scatterplot](https://seaborn.pydata.org/generated/seaborn.scatterplot.html#seaborn.scatterplot)**

```{python}
sns.scatterplot(x="capital_gain", y="capital_loss", data=df)
```

#### Using `seaborn.pairplot()` to reveal the relationships of different variables given the condition of `income` attributes


* **[seaborn.pairplot](https://seaborn.pydata.org/generated/seaborn.pairplot.html#seaborn.pairplot)**

```{python}
sns.pairplot(df, hue="income", palette='deep',
             height=3, diag_kind='kde', diag_kws=dict(shade=True), plot_kws=dict(s=20))
```

#### Using `seaborn.heatmap()` to capture the correlation between different attributes


* **[pandas.DataFrame.corr](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html)**
* **[seaborn.set](https://seaborn.pydata.org/generated/seaborn.set.html#seaborn.set)**
* **[seaborn.heatmap](https://seaborn.pydata.org/generated/seaborn.heatmap.html#seaborn.heatmap)**

```{python}
hmap = df.corr()
plt.subplots(figsize=(30, 18))
sns.set(font_scale=1.5)
ax = sns.heatmap(hmap, vmax=0.8, annot=True, cmap='BrBG', square=True)
ax.tick_params(labelsize=10) 
```

#### Using `seaborn.countplot()` with different conditions to show categorical multivariable's relationship


* **[pandas.DataFrame.shape](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html)**

```{python}
## Example: Citizens work in gov can earn more than those in private

## proof by plot
sns.countplot(y='work_class',hue = 'income',data=df)

## proof by calculation
private_df = df[df.work_class == 'Private']

gov_array = ['State-gov', 'Federal-gov', 'Local-gov']
gov_df = df[df.work_class.isin(gov_array)]

high_rate_in_private = private_df[private_df.income == 'high'].shape[0] / float(private_df.shape[0])
high_rate_in_gov = gov_df[gov_df.income == 'high'].shape[0] / float(gov_df.shape[0])
print('high_rate_in_private: ', high_rate_in_private)
print('high_rate_in_gov: ', high_rate_in_gov)
```

### Your Task

You are asked to inference the intrinsic correlations between different columns, e.g. `income` and `sex`.

Please proof whether the following assumptions are **True or Not** on our dataset? **Draw plots and calculate some values as the example to support your conclusion**.

1. Married citizens with spouse have higher chances of earning more than those who're unmarried/divorced/widowed/separated.
2. Males on an average earn more than females.
3. Higher Education can lead to higher income in most cases.


* **[pandas.concat](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html)**
* **[pandas.DataFrame.isin](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html)**
* **[pandas.DataFrame.replace](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.replace.html)**
* **[seaborn.countplot](https://seaborn.pydata.org/generated/seaborn.countplot.html)**

```{python}
# Question 8: Married citizens with spouse have higher chances of earning more than those who're unmarried/divorced/widowed/separated.
## 
## Your code here

married_stats = pd.concat([df[df.marital_status.isin(['Married-civ-spouse','Married-AF-spouse','Married-spouse-absent'])]])
married_stats.marital_status.replace({
    'Married-civ-spouse': 'Married-with-spouse',
    'Married-AF-spouse': 'Married-with-spouse',
    'Married-spouse-absent':'Married-with-spouse'}, inplace = True)

others_stats = pd.concat([df[~df.marital_status.isin(['Married-civ-spouse','Married-AF-spouse','Married-spouse-absent'])]])
others_stats.marital_status.replace({
    '([\w\W]+)': 'others',}, inplace = True, regex = True)

stats = pd.concat([married_stats,others_stats])

ax = sns.countplot(x = 'marital_status',hue = 'income', data = stats )
ax.tick_params(labelsize=15) 

plt.show()

married_high_ratio = married_stats[married_stats.income == 'high'].shape[0] / float(stats[stats.income == 'high'].shape[0])
others_high_ratio = others_stats[others_stats.income == 'high'].shape[0] / float(stats[stats.income == 'high'].shape[0])

high_married_ratio = married_stats[married_stats.income == 'high'].shape[0] / float(married_stats.shape[0])
high_others_ratio = others_stats[others_stats.income == 'high'].shape[0] / float(others_stats.shape[0])

print('married_high_ratio:%.4f'%(married_high_ratio))
print('others_high_ratio:%.4f'%(others_high_ratio))

print('high_married_ratio:%.4f'%(high_married_ratio))
print('high_others_ratio:%.4f'%(high_others_ratio))

```

### Conclusion 1: True
This is an analysis between two categorical variables: ``marital_status``(nominal) and ``income``(can be interpreted as ordinal but we don't need this attribute here). Hence, we use ``countplot`` from ``seaborn`` package to assist our analysis. Necessary ratio calculating is also included.

The results support the hypothesis that "Married citizens with spouse have higher chances of earning more than those who're unmarried/divorced/widowed/separated".

For one thing, among those who earn high income, over 85% of them are married; for another, within the group of married people, 44% of them have high income, while among those people who are not, only 6% of them have high income. Namely, most of the people who have high income are married with a spouse, and people with high income take up more proportion among married-with-spouse people than they do among people who are not. The trends can also be seen from the countplot figure.

Based on these, it is plausible that a married citizens with spouse have higher chances of earning more than those who're unmarried/divorced/widowed/separated.

```{python}
# Question 9: Males on an average make earn more than females.
## 
## Your code here
## 
ax1 = sns.countplot(x = 'sex',hue = 'income', data = stats )
plt.show()

male_avg = df.loc[(df['income'] == 'high') & (df['sex'] == 'Male')].shape[0] / float(df[df.sex == 'Male'].shape[0])
female_avg = df.loc[(df['income'] == 'high') & (df['sex'] == 'Female')].shape[0] / float(df[df.sex == 'Female'].shape[0])

print('male_avg:%.4f'%(male_avg))
print('female_avg:%.4f'%(female_avg))
```

### Conclusion 2: True

This is an analysis between two categorical variables: ``sex``(nominal) and ``income``. Since we need to tackle averages, we need to treat income as an ordinal variable and encode it.

The easiest way to encode is to set ``high = 1`` and ``low = 0``, thus the average of income of one sex can be simplified as the number of high-income people over the size of this group. Also the countplot is useful in this sense.

The results support the hypothesis that "Males on an average earn more than females."

We calculate the average income of male and female and the results show that male's average income are higher than that of females. The countplot shows the same, which depicts that high-income males take up bigger proportion among all males than females do.

Based on these, it is plausible that males on an average earn more than females.

```{python}
# Question 10: Higher Education can lead to higher income in most cases.
## Your code here
## education,education_degree

ax = sns.boxplot(x="income", y="education_degree", data=df)
plt.show()

sns.distplot(df[df.income == 'high']['education_degree'], kde_kws={'label': 'high'})
sns.distplot(df[df.income == 'low']['education_degree'], kde_kws={'label': 'low'})
plt.show()

no_college_stats = pd.concat([df[df.education.isin(['dropout','HighGrad'])]])
postgrad_stats = pd.concat([df[df.education.isin(['Master','Doctorate'])]])

no_college_high_ratio = no_college_stats[no_college_stats.income == 'high'].shape[0] / float(no_college_stats.shape[0])
postgrad_high_ratio = postgrad_stats[postgrad_stats.income == 'high'].shape[0] / float(postgrad_stats.shape[0])

print('no_college_high_ratio:%.4f'%(no_college_high_ratio))
print('postgrad_high_ratio:%.4f'%(postgrad_high_ratio))
```

### Conclusion 3: True
Three categorical variables are related to this analysis: ``education``(nominal), ``education_degree``(ordinal), and ``income``(can be interpreted as ordinal but we don't need this attribute here). However, the former two variables are highly correlated by such mappings:

education | education_degree
--|--
'dropout' | < 8
'HighGrad' | 9
'Some-college' | 10
'Community College' | 11-12
'Bachelors'| 13
'Masters'| 14-15
'Doctorate'| 16

In this sense, to analyze ``education`` against ``income`` is equivalent to analyze ``education_degree`` against ``income``.

The results support the hypothesis that "Higher Education can lead to higher income in most cases".

A perfect choice to test the hypothesis is using ``boxplot``, which shows the median, the quartiles, and outliers of a numerical variable. Distribution plot can also be useful to overview the distribution of education degree among people with different income. 

The boxplot shows that people with high income have higher median education degree value than people with low income. The quartiles even show that 75%(literally the majority) of high-income people have higher degree than 75% of low-income people. Modes shown in the distribution plot reveal the same.

Also, if we define those who don't take any college programs as low-education degree people (<10), and postgraduates (education degree > 13) as high-education degree people, we can calculate their proportion among people with high income. The result shows that postgraduates take up nearly three quarters of the high-income group while dropouts and high-school graduates only share less than 1/7.

Based on these, it is plausible that higher education can lead to higher income in most cases.
